### ISSUE TITLE
Umbrella Issue: Release 1.3

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/manifests#1777]
### Steps for Release Candidate

1. Upstream WGs: resolve blocking PRs
    - Docs
        - [x] Move Platforms under Distributions:
            - [x] Google: https://github.com/kubeflow/website/pull/2547
            - [x] Openshift: https://github.com/kubeflow/website/pull/2550
            - [x] IBM: https://github.com/kubeflow/website/pull/2549
            - [x] Azure: https://github.com/kubeflow/website/pull/2548
    - Manifests
        - [x] Istio 1.9 manifests: https://github.com/kubeflow/manifests/issues/1753
        - [x] Consolidate multiple manifests versions into one: https://github.com/kubeflow/manifests/issues/1769
    - Notebooks
        - [x] Fixes for the Tensorboards web app: https://github.com/kubeflow/kubeflow/pull/5693
        - [x] Volumes Manager UI: https://github.com/kubeflow/kubeflow/pull/5684
        - [x] Manifests for the Volumes web app: https://github.com/kubeflow/kubeflow/pull/5728
        - [x] Manifests for Tensorboards web app: https://github.com/kubeflow/kubeflow/pull/5727
        - [x] Manifests for Tensorboard controller: https://github.com/kubeflow/kubeflow/pull/5730
        - [x] JWA changes to enable VS-Code and RStudio support: https://github.com/kubeflow/kubeflow/pull/5646
        - [x] https://github.com/kubeflow/kubeflow/pull/5624
        - [x] https://github.com/kubeflow/kubeflow/pull/5711
        - [x] AutoML entry in the CentralDashboard https://github.com/kubeflow/kubeflow/issues/5750
    - Training
        - [x] XGBoost manifests: https://github.com/kubeflow/xgboost-operator/issues/115
    - Pipelines
        - [x] Project for 1.3: https://github.com/kubeflow/pipelines/projects/12
        - [x] https://github.com/kubeflow/pipelines/pull/5344

2. Upstream WGs: release artifacts (images, manifests), give manifests-wg the desired git revisions: https://github.com/kubeflow/manifests/issues/1775
    - [x] AutoML
    - [x] Pipelines
    - [x] Serving
    - [x] Notebooks
        - [x] Merge PR for establishing release process:  https://github.com/kubeflow/kubeflow/pull/5746
        - [x] Cut release branch: https://github.com/kubeflow/kubeflow/issues/5772
        - [x] Merge release PR: https://github.com/kubeflow/kubeflow/pull/5776
        - [x] Fix postsubmit error: https://github.com/kubeflow/kubeflow/issues/5784
        - [x] Tag release commit: https://github.com/kubeflow/kubeflow/issues/5788
    - [x] Training
3. Manifests WG: sync manifests from upstream app releases to manifests repo: https://github.com/kubeflow/manifests/issues/1775
4. Manifests WG: test and add instructions to build + install manifests with kubectl + kustomize upstream: https://github.com/kubeflow/manifests/issues/1776
5. Manifests WG: Cut release candidate branch in manifests.
6. Distributions: Use instructions from wg-manifests for how to use kustomizations and create distributions for 1.3. https://github.com/kubeflow/manifests/issues/1798

### Timeline

Step 1+2: __Wednesday, EOD, 2021-03-24 [Pacific Time]__  ✔️ 
Step 3+4+5: __Monday, EOD 2021-03-29 [Pacific Time]__ ✔️ 
Step 6: __Tuesday, EOD 2021-04-06 [Pacific Time]__ ✔️

**Comment by yanniszark** [comment]
cc @kubeflow/wg-automl-leads
cc @kubeflow/wg-deployment-leads
cc @kubeflow/wg-manifests-leads
cc @kubeflow/wg-notebooks-leads
cc @kubeflow/wg-pipeline-leads
cc @kubeflow/wg-serving-leads
cc @kubeflow/wg-training-leads
cc @RFMVasconcelos

**Comment by thesuperzapper** [comment]
@yanniszark 

Can we change the description of Step 6 to say: "freeze on `v1.3-branch` in `kubeflow/manifests`"

Also can we add the following dates to the description to help people see

Step 1+2: __Wednesday, EOD, 2021-03-24 [Pacific Time]__ 
Step 3+4+5: __Monday, EOD 2021-03-29 [Pacific Time]__ 
Step 6: __Tuesday, EOD 2021-04-06 [Pacific Time]__

**Comment by Jeffwan** [comment]
https://github.com/kubeflow/xgboost-operator/issues/115 has been addressed. I mark it as done

**Comment by Bobgy** [comment]
FYI, I think we should add @yanniszark as a member of release-team at the start of the release process: https://github.com/kubeflow/internal-acls/pull/441, so that he would be able to cut releases easily without my help.

**Comment by thesuperzapper** [comment]
@yanniszark @kubeflow/wg-manifests-leads just wanted to highlight a MUCH easier (and more sustainable) option than copying all the upstream manifests into `kubeflow/manifests`!

In Kustomize, you can directly reference the upstream repo, at a specific version tag.

For example, referencing `crud-web-apps` in `kubeflow/kubeflow`: 
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/crud-web-apps/jupyter/manifests/overlays/istio?ref=v1.3-branch
```

Should save lots of time/effort!

**Comment by DavidSpek** [comment]
@yanniszark Just wanted to let you know that you don't actually need to copy all the upstream manifests into this repo. It is much more user friendly to just reference them. This way, users don't need to dig through the entire mountain of manifests to change what they need, and all they have is a single simple file that they can add their own customizations to (for some common settings people want to change like the images for the JWA you can already include the file). Example:
`kustomization.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/crud-web-apps/jupyter/manifests/overlays/istio?ref=v1.3-branch

patchesStrategicMerge:
- spawner_ui_config.yaml

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app
  newName: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app
  newTag: v1.3.0-rc.0
```
`spawner_ui_config.yaml`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  spawner_ui_config.yaml: |
    # Configuration file for the Jupyter UI.
    #
    # Each Jupyter UI option is configured by two keys: 'value' and 'readOnly'
    # - The 'value' key contains the default value
    # - The 'readOnly' key determines if the option will be available to users
    #
    # If the 'readOnly' key is present and set to 'true', the respective option
    # will be disabled for users and only set by the admin. Also when a
    # Notebook is POSTED to the API if a necessary field is not present then
    # the value from the config will be used.
    #
    # If the 'readOnly' key is missing (defaults to 'false'), the respective option
    # will be available for users to edit.
    #
    # Note that some values can be templated. Such values are the names of the
    # Volumes as well as their StorageClass
    spawnerFormDefaults:
      image:
        # The container Image for the user's Jupyter Notebook
        value: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy:master-1831e436
        # The list of available standard container Images
        options:
          - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy:master-1831e436
          - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-full:master-1831e436
          - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-cuda-full:master-1831e436
          - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-full:master-1831e436
          - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-cuda-full:master-1831e436
      imageVSCode:
        # The container Image for the user's VS-Code Server
        value: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/codeserver-python:master-1831e436
        # The list of available standard container Images
        options:
          - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/codeserver-python:master-1831e436
      imageRStudio:
        # The container Image for the user's RStudio Server
        value: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/rstudio-tidyverse:master-164fa2ea
        # The list of available standard container Images
        options:
          - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/rstudio-tidyverse:master-164fa2ea
      allowCustomImage: true
      imagePullPolicy:
        value: IfNotPresent
        readOnly: false
      cpu:
        # CPU for user's Notebook
        value: '0.5'
        readOnly: false
      memory:
        # Memory for user's Notebook
        value: 1.0Gi
        readOnly: false
      workspaceVolume:
        # Workspace Volume to be attached to user's Notebook
        # Each Workspace Volume is declared with the following attributes:
        # Type, Name, Size, MountPath and Access Mode
        value:
          type:
            # The Type of the Workspace Volume
            # Supported values: 'New', 'Existing'
            value: New
          name:
            # The Name of the Workspace Volume
            # Note that this is a templated value. Special values:
            # {notebook-name}: Replaced with the name of the Notebook. The frontend
            #                  will replace this value as the user types the name
            value: 'workspace-{notebook-name}'
          size:
            # The Size of the Workspace Volume (in Gi)
            value: '10Gi'
          mountPath:
            # The Path that the Workspace Volume will be mounted
            value: /home/jovyan
          accessModes:
            # The Access Mode of the Workspace Volume
            # Supported values: 'ReadWriteOnce', 'ReadWriteMany', 'ReadOnlyMany'
            value: ReadWriteOnce
          class:
            # The StrageClass the PVC will use if type is New. Special values are:
            # {none}: default StorageClass
            # {empty}: empty string ""
            value: '{none}'
        readOnly: false
      dataVolumes:
        # List of additional Data Volumes to be attached to the user's Notebook
        value: []
        # Each Data Volume is declared with the following attributes:
        # Type, Name, Size, MountPath and Access Mode
        #
        # For example, a list with 2 Data Volumes:
        # value:
        #   - value:
        #       type:
        #         value: New
        #       name:
        #         value: '{notebook-name}-vol-1'
        #       size:
        #         value: '10Gi'
        #       class:
        #         value: standard
        #       mountPath:
        #         value: /home/jovyan/vol-1
        #       accessModes:
        #         value: ReadWriteOnce
        #       class:
        #         value: {none}
        #   - value:
        #       type:
        #         value: New
        #       name:
        #         value: '{notebook-name}-vol-2'
        #       size:
        #         value: '10Gi'
        #       mountPath:
        #         value: /home/jovyan/vol-2
        #       accessModes:
        #         value: ReadWriteMany
        #       class:
        #         value: {none}
        readOnly: false
      gpus:
        # Number of GPUs to be assigned to the Notebook Container
        value:
          # values: "none", "1", "2", "4", "8"
          num: "none"
          # Determines what the UI will show and send to the backend
          vendors:
            - limitsKey: "nvidia.com/gpu"
              uiName: "NVIDIA"
            - limitsKey: "amd.com/gpu"
              uiName: "AMD"
          # Values: "" or a `limits-key` from the vendors list
          vendor: ""
        readOnly: false
      shm:
        value: true
        readOnly: false
      configurations:
        # List of labels to be selected, these are the labels from PodDefaults
        # value:
        #   - add-gcp-secret
        #   - default-editor
        value: []
        readOnly: false
      affinityConfig:
        # The default `configKey` from the options list
        # If readonly, the default value will be the only option
        value: "none"
        # The list of available affinity configs
        options: []
        # # (DESC) Pod gets an exclusive "n1-standard-2" Node
        # # (TIP) set PreferNoSchedule taint on this node-pool
        # # (TIP) enable cluster-autoscaler on this node-pool
        # # (TIP) dont let users request more CPU/MEMORY than the size of this node
        # - configKey: "exclusive__n1-standard-2"
        #   displayName: "Exclusive: n1-standard-2"
        #   affinity:
        #     # (Require) Node having label: `node_pool=notebook-n1-standard-2`
        #     nodeAffinity:
        #       requiredDuringSchedulingIgnoredDuringExecution:
        #         nodeSelectorTerms:
        #           - matchExpressions:
        #               - key: "node_pool"
        #                 operator: "In"
        #                 values:
        #                   - "notebook-n1-standard-2"
        #     # (Require) Node WITHOUT existing Pod having label: `notebook-name`
        #     podAntiAffinity:
        #       requiredDuringSchedulingIgnoredDuringExecution:
        #         - labelSelector:
        #             matchExpressions:
        #               - key: "notebook-name"
        #                 operator: "Exists"
        #           namespaces: []
        #           topologyKey: "kubernetes.io/hostname"
        readOnly: false
      tolerationGroup:
        # The default `groupKey` from the options list
        # If readonly, the default value will be the only option
        value: "none"
        # The list of available tolerationGroup configs
        options: []
        # - groupKey: "group_1"
        #   displayName: "Group 1: description"
        #   tolerations:
        #     - key: "key1"
        #       operator: "Equal"
        #       value: "value1"
        #       effect: "NoSchedule"
        #     - key: "key2"
        #       operator: "Equal"
        #       value: "value2"
        #       effect: "NoSchedule"
        readOnly: false
```

I've done this for almost all the manifest already [here](https://github.com/kubeflow-onprem/ArgoFlow/tree/master/kubeflow). 
/cc @thesuperzapper as he suggested I point this out to you in this issue.

**Comment by connorlwilkes** [comment]
> @yanniszark Just wanted to let you know that you don't actually need to copy all the upstream manifests into this repo. It is much more user friendly to just reference them. This way, users don't need to dig through the entire mountain of manifests to change what they need, and all they have is a single simple file that they can add their own customizations to (for some common settings people want to change like the images for the JWA you can already include the file). Example:
> `kustomization.yaml`:
> 
> ```yaml
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> 
> resources:
> - github.com/kubeflow/kubeflow/components/crud-web-apps/jupyter/manifests/overlays/istio?ref=v1.3-branch
> 
> patchesStrategicMerge:
> - spawner_ui_config.yaml
> 
> images:
> - name: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app
>   newName: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app
>   newTag: v1.3.0-rc.0
> ```
> 
> `spawner_ui_config.yaml`:
> 
> ```yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: config
> data:
>   spawner_ui_config.yaml: |
>     spawnerFormDefaults:
>       image:
>         # The container Image for the user's Jupyter Notebook
>         value: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy:master-1831e436
>         # The list of available standard container Images
>         options:
>           - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy:master-1831e436
>           - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-full:master-1831e436
>           - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-cuda-full:master-1831e436
>           - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-full:master-1831e436
>           - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-cuda-full:master-1831e436
>       imageVSCode:
> ...
> ```
> 
> I've done this for almost all the manifest already [here](https://github.com/kubeflow-onprem/ArgoFlow/tree/master/kubeflow).
> /cc @thesuperzapper as he suggested I point this out to you in this issue.

I seem to recall previously this was impossible due to the fact that folders had bases 'above' them in the directory tree which I don't recall kustomize liking. Not sure at a cursory glance that this is fixed here either?

**Comment by thesuperzapper** [comment]
@connorlwilkes nah, thats just because some Kubeflow manifest need the `--load_restrictor none` flag.

We should probably design the manifest to not need this flag @yanniszark?

**Comment by DavidSpek** [comment]
@thesuperzapper Actually, only very few manifests need the `--load_restrictor` flag. From what I've seen so far only the Katib manifests need this (and the KNative manifests because the file references were accidentally not removed, see: https://github.com/kubeflow/manifests/pull/1784).

**Comment by connorlwilkes** [comment]
> @connorlwilkes nah, thats just because some Kubeflow manifest need the `--load_restrictor none` flag.
> 
> We should probably design the manifest to not need this flag @yanniszark?

But when I have the following kustomization.yaml:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
patchesJson6902:
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: StatefulSet
    name: application-controller-stateful-set
    version: v1
    namespace: kubeflow
resources:
- github.com/kubeflow/manifests/application/v3?ref=v1.2.0
```

and I run:
`kustomize build --load_restrictor=none .`

I get the following error relating to 'security issues' which I believe load_restrictor is supposed to ignore:

```
Error: accumulating resources: 2 errors occurred:
	* accumulateFile error: "accumulating resources from 'github.com/kubeflow/manifests/application/v3?ref=v1.2.0': open /Users/wilkesc/tmp/github.com/kubeflow/manifests/application/v3?ref=v1.2.0: no such file or directory"
	* accumulateDirector error: "recursed accumulation of path '/private/var/folders/vl/_pz1d0nx5hb8hsr78ws3r94sfd_vw5/T/kustomize-819300163/application/v3': accumulating resources: 2 errors occurred:\n\t* accumulateFile error: \"accumulating resources from '../application/base/cluster-role.yaml': security; file '/private/var/folders/vl/_pz1d0nx5hb8hsr78ws3r94sfd_vw5/T/kustomize-819300163/application/application/base/cluster-role.yaml' is not in or below '/private/var/folders/vl/_pz1d0nx5hb8hsr78ws3r94sfd_vw5/T/kustomize-819300163/application/v3'\"\n\t* loader.New error: \"error loading ../application/base/cluster-role.yaml with git: url lacks host: ../application/base/cluster-role.yaml, dir: got file 'cluster-role.yaml', but '/private/var/folders/vl/_pz1d0nx5hb8hsr78ws3r94sfd_vw5/T/kustomize-819300163/application/application/base/cluster-role.yaml' must be a directory to be a root, get: invalid source string: ../application/base/cluster-role.yaml\"\n\n"
```

**Comment by DavidSpek** [comment]
@connorlwilkes Try `--load-restrictor=LoadRestrictionsNone` instead.

**Comment by connorlwilkes** [comment]
> --load-restrictor=LoadRestrictionsNone

I am using kustomize version 3.10 FYI. With: `kustomize build --load_restrictor=LoadRestrictionsNone .` I get the same error

**Comment by yanniszark** [comment]
@thesuperzapper @DavidSpek @connorlwilkes thanks a lot for the discussion and the suggestions for improvement.
I would love to take a look after we have made the release. Since this is the release tracking issue, could you open a new issue(s) to track the potential improvements?
We can continue the discussion(s) there.

**Comment by DavidSpek** [comment]
@yanniszark Once I get a bit further with my work on the manifests I'll create a new issue. I'll also ping you about some other things I've found on slack.

**Comment by DavidSpek** [comment]
@yanniszark After discussing with @Bobgy it might be a blocking issue for the distributions to not include the new Jupyter Web App which allow for spawning VSCode and RStudio notebook servers due to the use of their respective logos. I'll be looking into a mitigation route for distributions to avoid potential problems here, but they will need to be notified about this. 

@Bobgy Also suggested to bring up that RStudio is licensed under the AGPL license, so the example image with RStudio might also be something distributions need to look into if they can include this or not. The above mitigation will also address this problem, but it is something distributions might want to look into separately.

**Comment by DavidSpek** [comment]
@yanniszark There is a regression in the Jupyter Web App that needs fixing so this might be a blocker (fix should almost be ready though).

**Comment by RFMVasconcelos** [comment]
@yanniszark both `kubeflow/kubeflow` and `kubeflow/manifests` repos still have release v1.2 tag + changelog. We should update this. Is there a plan in place?

**Comment by frezbo** [comment]
Even though KF 1.3 is releases, the GitHub tags shows v1.2 which is quite confusing

**Comment by toshi-k** [comment]
Although, the latest release is updated to KF1.3 in this repo, it contains v.1.3.0-rc1 images.
Don't you update upstream images ?
https://github.com/kubeflow/manifests/releases/tag/v1.3.0

**Comment by thesuperzapper** [comment]
@toshi-k for the images from the `kubeflow/kubeflow` (stuff like Notebooks, Central-Dashboard, etc), there were no changes after `v1.3.0-rc1`, and we forogt to re-tag the images as `v1.3.0`, but don't worry, they are the correct images.

**Comment by DavidSpek** [comment]
@thesuperzapper the tag for v1.3.0 has been created, just the GitHub release hasn't yet.

**Comment by kimwnasptd** [comment]
Closing this issue since 1.3 is released and we also did a retrospective.
