### ISSUE TITLE
Security WG roadmap for KF 1.9

### ISSUE THREAD

**Issue by rimolive** [kubeflow/manifests#2598]
- [x] https://github.com/kubeflow/manifests/pull/2544
- [x] https://github.com/kubeflow/manifests/pull/2546
- [x] https://github.com/kubeflow/manifests/pull/2527
- [ ] https://github.com/kubeflow/kubeflow/pull/7325 i am waiting for this to get merged by kubeflow/kubeflow maintainers
- [x] https://github.com/kubeflow/manifests/pull/2457 The KSC has to decide on that. From the technical side it is ready
- [x] https://github.com/kubeflow/manifests/pull/2329
- [x] https://github.com/kubeflow/manifests/pull/2658 as preparation for trivy

**Comment by StefanoFioravanzo** [comment]
Hello @akgraner @juliusvonkohout, this is a kind reminder that Monday, March 4th will be our Kubeflow 1.9 release development checkpoint, we will be halfway through our dev cycle, and we expect most of the work to be well underway.

Can you please acknowledge your status with respect to your roadmap, comment on the progress made so far, and provide an assessment of the work that remains?

Does the comment above reflect the work that will be delivered as part of Kubeflow 1.9? Is it up to date?

**Comment by StefanoFioravanzo** [comment]
@juliusvonkohout  Why do you say a merged PR (first one) is in progress? Merged PR should mean "checked" box I guess. If that's not valid, what else needs to be done?

**Comment by StefanoFioravanzo** [comment]
@juliusvonkohout  Why do you say a merged PR (first one) is in progress? Merged PR should mean "checked" box I guess. If that's not valid, what else needs to be done?

**Comment by juliusvonkohout** [comment]
I checked the boxes for you :-D

**Comment by rimolive** [comment]
This is done
