### ISSUE TITLE
Kubeflow Platform (Manifests & Security WG) roadmap for KF 1.10.0

### ISSUE THREAD

**Issue by juliusvonkohout** [kubeflow/manifests#2763]
### Describe your issue

Tracker for 1.10 @rimolive @kimwnasptd 
Follow up of https://github.com/kubeflow/manifests/issues/2598 and https://github.com/kubeflow/manifests/issues/2592

We are looking for volunteers and I already mentored over 20 people, so please reach out if you want to help.

Organizational:
- [x] https://github.com/kubeflow/manifests/issues/2804
- [x] https://github.com/kubeflow/manifests/issues/2922
- [ ] https://github.com/kubeflow/manifests/issues/2783
- [x] https://github.com/kubeflow/community/pull/725
- [x] https://github.com/kubeflow/kubeflow/pull/7618
- [x] Expose from /contrib ray and seldon in the example.yaml (commented out)
- [ ]  Kserve web application: can you help with rebasing/forking the 5 PRs here and merging them https://github.com/kserve/models-web-app/pulls. We also need someone to go trough https://github.com/kserve/models-web-app/issues and close or confirm whether they are still valid.
- [x] https://github.com/kubeflow/manifests/issues/2912

documentation:
- [x] https://github.com/kubeflow/manifests/pull/2930
- [x] https://github.com/kubeflow/manifests/pull/2911

chore:
- [x] https://github.com/kubeflow/manifests/pull/2919
- [x] https://github.com/kubeflow/manifests/pull/2917
- [x] https://github.com/kubeflow/manifests/pull/2916
- [x] https://github.com/kubeflow/manifests/pull/2908 `--server-side --force-conflicts` since CRDs became too big in Kserve 0.14.0
- [x] https://github.com/kubeflow/manifests/pull/2903
- [x] https://github.com/kubeflow/manifests/pull/2890
- [x] https://github.com/kubeflow/manifests/pull/2929 (cilium compatibility)
- [x] https://github.com/kubeflow/manifests/pull/2920
- [x] https://github.com/kubeflow/manifests/pull/2911

Security external:
- [ ] https://github.com/kubeflow/pipelines/pull/11134
- [ ] https://github.com/kubeflow/pipelines/issues/9889
- [ ] https://github.com/kubeflow/pipelines/issues/7878
- [ ] https://github.com/kubeflow/pipelines/pull/7725
- [ ] https://github.com/kubeflow/pipelines/issues/4790
- [x] https://github.com/kubeflow/pipelines/pull/11159 as follow up of https://github.com/kubeflow/pipelines/pull/10950
- [x] https://github.com/kubeflow/pipelines/issues/10397
- [x] https://github.com/kubeflow/manifests/issues/2433

Performance / Denial of service:
- [ ] https://github.com/kubeflow/kubeflow/pull/7080
- [ ] https://github.com/kubeflow/notebooks/issues/85 a single bad CR can kill the controller of v1 Workbenches
- [ ] https://github.com/kubeflow/notebooks/issues/93
- [ ] NOT SOLVED Support big (5+ GB) s3 artifacts in pipelines https://github.com/argoproj/argo-workflows/issues/9525 and https://github.com/argoproj/argo-workflows/issues/1322 (they are not solved)

Security JWTs:
- [x] https://github.com/kubeflow/manifests/pull/2748
- [x] https://github.com/kubeflow/manifests/issues/2747
- [x] https://github.com/kubeflow/manifests/pull/2753

Rootless Kubeflow & Istio:
- [ ] https://github.com/kubeflow/manifests/issues/2528
- [ ] Make istio CNI the default and set the kserve-needed annotation across all Pods. We should use the new "Values.gateways.seccompProfile" and securitycontext to get rid of the manual patch at https://github.com/kubeflow/manifests/blob/26d970d33dd64a8d175d92dd739f0198551336d2/.github/workflows/pss_test.yaml#L35-L45. First PR: https://github.com/kubeflow/manifests/pull/2907
- [ ] https://github.com/kubeflow/manifests/issues/2676

Rest:
- [ ] https://github.com/kubeflow/pipelines/issues/10988
- [ ] https://github.com/kubeflow/kubeflow/pull/7547
- [x] https://github.com/kubeflow/manifests/issues/2727
- [x] https://github.com/kubeflow/manifests/issues/2765
- [x] https://github.com/kubeflow/kubeflow/pull/7325
- [x] https://github.com/kubeflow/manifests/issues/2742
- [x] https://github.com/kubeflow/manifests/issues/2514
- [x] https://github.com/kubeflow/manifests/issues/2685
- [x] https://github.com/kubeflow/manifests/issues/2718
- [x] https://github.com/kubeflow/pipelines/pull/11067

**Comment by kimwnasptd** [comment]
(Orthogonal question, but why is this called `Kubeflow Platform` and includes Manifests and Security WGs in it? 

Especially once we'll have the repos broken up after the discussion in https://github.com/kubeflow/kubeflow/issues/7549#issuecomment-2181054114

**Comment by thesuperzapper** [comment]
Similar to what @kimwnasptd said, it's hard to imagine that "Kubeflow Platform" should not also involve the distribution owners? I am not sure we should be calling the meetings "Kubeflow Platform" if they are only referring to Manifests/Security WGs.

**Comment by andreyvelich** [comment]
> (Orthogonal question, but why is this called `Kubeflow Platform` and includes Manifests and Security WGs in it?
> 
> Especially once we'll have the repos broken up after the discussion in [kubeflow/kubeflow#7549 (comment)](https://github.com/kubeflow/kubeflow/issues/7549#issuecomment-2181054114)

@kimwnasptd The main motivation is to identify contributors who can maintain [Kubeflow Platform components](https://www.kubeflow.org/docs/started/introduction/#what-is-kubeflow-platform). E.g. Kubeflow Manifests, Profile Controller, KFAM, Central Dashboard, etc. So if users have any questions about these components they can join the Kubeflow Platform community calls.
Since @juliusvonkohout was driving the security effort around Kubeflow ecosystem, he included the security roadmap to the Kubeflow Platform discussion.

From my perspective, distributions should certainly join those meetings since they are main consumers of Kubeflow Manifests.

**Comment by juliusvonkohout** [comment]
@kimwnasptd it is in line with https://github.com/kubeflow/community/pull/725#issuecomment-2180215762

**Comment by juliusvonkohout** [comment]
The follow up is https://github.com/kubeflow/manifests/issues/3038
