### ISSUE TITLE
add applications overlays 

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/manifests#489]
- [x] add application overlays for gcp #472
- [x] add application overlays for pipeline #469
- [x] add application overlay for basic-auth-ingress #467
- [x] update application overlays for centraldashboard #459
- [x] add application overlay for aws #456
- [x] add application overlay for notebook-controller #450
- [x] add application overlay to spartakus #479
- [x] update application overlay for metadata #480
- [x] add application overlays for profiles #482
- [x] add application overlay for pytorch-job-crds #483
- [x] update application overlay for tf-job-operator #487
- [x] add application overlay for tf-job-crds #488
- [x] upgrade all application instance labels to v0.7.0 #524

**Comment by richardsliu** [comment]
@kkasravi We can close this now right?

**Comment by kkasravi** [comment]
yes - i can close
